modLoader="javafml"
loaderVersion="[31,)"
[[mods]]
modId="ivrench"
version="${file.jarVersion}"
displayName="Inverted Enchantments"
authors="MisterPlus, Hao_cen"
displayURL="https://www.curseforge.com/minecraft/mc-mods/inverted-enchantments"
description='''
A mod that adds every inverted version of vanilla enchants.
'''